#
#
# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
#
version: '3.8'
services:
    pushgateway:
        container_name: pushgateway
        network_mode: host
        pid: host
        restart: unless-stopped
        image: prom/pushgateway
    prometheus:
        container_name: prometheus
        network_mode: host
        pid: host
        restart: unless-stopped
        user: root
        volumes:
            - '/home/$cfn_cluster_user/__MONITORING_DIR__/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
            - 'prometheus-data:/prometheus'
        image: prom/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--storage.tsdb.path=/prometheus'
            - '--web.console.libraries=/usr/share/prometheus/console_libraries'
            - '--web.console.templates=/usr/share/prometheus/consoles'
            - '--web.external-url=/prometheus/'
            - '--web.route-prefix=/'
    grafana:
        container_name: grafana
        network_mode: host
        pid: host
        restart: unless-stopped
        user: root
        environment:
            - 'GF_AUTH_ANONYMOUS_ENABLED=true'
            - 'GF_SECURITY_ADMIN_PASSWORD=Grafana4PC!'
            - 'GF_SERVER_ROOT_URL=http://%(domain)s/grafana/'
            - 'GF_SECURITY_ALLOW_EMBEDDING=true'
        volumes:
            - '/home/$cfn_cluster_user/__MONITORING_DIR__/grafana:/etc/grafana/provisioning'
            - 'grafana-data:/var/lib/grafana'
        image: grafana/grafana
    prometheus-node-exporter:
        container_name: node-exporter
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/:/host:ro,rslave'
        image: quay.io/prometheus/node-exporter
        command:
            - '--path.rootfs=/host'
    nginx:
        container_name: nginx
        network_mode: host
        pid: host
        restart: unless-stopped
        volumes:
            - '/home/$cfn_cluster_user/__MONITORING_DIR__/nginx/conf.d:/etc/nginx/conf.d/'
            - '/home/$cfn_cluster_user/__MONITORING_DIR__/nginx/ssl:/etc/ssl/'
            - '/home/$cfn_cluster_user/__MONITORING_DIR__/www:/usr/share/nginx/html'
        image: nginx
volumes:
    prometheus-data:
    grafana-data:
