{
 "title": "GPU Nodes",
 "description": "Dashboard to visualize data from the NVIDIA Data Center GPU Manager (DCGM)",
 "tags": [ "GPU" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "nodename",
    "label": "Node Name",
    "query": {
     "query": "label_values(node_uname_info{job=~\"ec2_instances\",instance_type=~\"[pg][2-4].*\"}, nodename)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Name",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{nodename=~\"$nodename\"}"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{nodename=\"$nodename\"}"
    }
   ]
  },
  {
   "title": "GPU Total Utilization",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{Hostname=\"$nodename\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Total Power",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{Hostname=\"$nodename\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Avg. Temperature",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_TEMP{Hostname=\"$nodename\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Decored Utilization",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_DEC_UTIL{Hostname=\"$nodename\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Encored Utilization",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_ENC_UTIL{Hostname=\"$nodename\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Mem Util.",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{Hostname=\"$nodename\"}/(DCGM_FI_DEV_FB_FREE{Hostname=\"$nodename\"}+DCGM_FI_DEV_FB_USED{Hostname=\"$nodename\"})*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_SM_CLOCK{Hostname=\"$nodename\"}*1000000",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "DCGM_FI_DEV_MEM_CLOCK{Hostname=\"$nodename\"}*1000000",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "NVLINK Bandwidth",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{Hostname=\"$nodename\"}[$__interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max by(gpu) (DCGM_FI_DEV_GPU_UTIL{Hostname=\"$nodename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max by(gpu) (DCGM_FI_DEV_GPU_TEMP{Hostname=\"$nodename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PCIe Throughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_PCIE_TX_THROUGHPUT{Hostname=\"$nodename\"}",
     "legendFormat": "GPU{{gpu}}_Tx"
    },
    {
     "expr": "DCGM_FI_DEV_PCIE_RX_THROUGHPUT{Hostname=\"$nodename\"}",
     "legendFormat": "GPU{{gpu}}_Rx"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "max by(gpu) (DCGM_FI_DEV_SM_CLOCK{Hostname=\"$nodename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "max by(gpu) (DCGM_FI_DEV_POWER_USAGE{Hostname=\"$nodename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "max by(gpu) (DCGM_FI_DEV_FB_USED{Hostname=\"$nodename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Memory Clocks",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "max by(gpu) (DCGM_FI_DEV_MEM_CLOCK{Hostname=\"$nodename\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Mem Cpy Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "max by(gpu) (DCGM_FI_DEV_MEM_COPY_UTIL{Hostname=\"$nodename\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}