{
 "title": "Jobs Details",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "IP",
    "query": "label_values(node_uname_info{instance_id=~\"$instance_id\"},instance)"
   },
   {
    "name": "maxmount",
    "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext4|xfs\"}) by (mountpoint))))"
   },
   {
    "name": "env",
    "label": "环境",
    "query": "label_values(node_exporter_build_info,env)"
   },
   {
    "name": "name",
    "label": "名称",
    "query": "label_values(node_exporter_build_info{env=~'$env'},name)"
   },
   {
    "name": "jobid",
    "label": "JobID",
    "query": {
     "query": "label_values(node_uname_info{job=~\"ec2_instances\"}, jobid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Cores",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(count(node_cpu_seconds_total{jobid=~\"$jobid\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{jobid=~\"$jobid\",mode=\"system\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_System"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{jobid=~\"$jobid\",mode=\"user\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_User"
    },
    {
     "expr": "avg(irate(node_cpu_seconds_total{jobid=~\"$jobid\",mode=\"iowait\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Iowait"
    },
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{jobid=~\"$jobid\",mode=\"idle\"}[30m])) by (instance)",
     "legendFormat": "{{instance}}_Total"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "bps", "label": "transmit（-）/receive（+）" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{jobid=~'$jobid',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_receive"
    },
    {
     "expr": "irate(node_network_transmit_bytes_total{jobid=~'$jobid',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[30m])*8",
     "legendFormat": "{{instance}}_{{device}}_transmit"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{jobid=~\"$jobid\"}",
     "legendFormat": "{{instance}}_Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{jobid=~\"$jobid\"} - node_memory_MemAvailable_bytes{jobid=~\"$jobid\"}",
     "legendFormat": "{{instance}}_Used"
    },
    {
     "expr": "node_memory_MemAvailable_bytes{jobid=~\"$jobid\"}",
     "legendFormat": "{{instance}}_Avaliable"
    }
   ]
  },
  {
   "title": "Disk R/W Data",
   "type": "graph",
   "description": "Per second read / write bytes ",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{jobid=~\"$jobid\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read bytes"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{jobid=~\"$jobid\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Written bytes"
    }
   ]
  },
  {
   "title": "Disk Space Used Basic",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1-(node_filesystem_free_bytes{jobid=~'$jobid',fstype=~\"ext4|xfs\"} / node_filesystem_size_bytes{jobid=~'$jobid',fstype=~\"ext4|xfs\"})",
     "legendFormat": "{{instance}}：{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Open  File Descriptor(left)/Context switches(right)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{jobid=~\"$jobid\"}",
     "legendFormat": "filefd_{{instance}}"
    },
    {
     "expr": "irate(node_context_switches_total{jobid=~\"$jobid\"}[30m])",
     "legendFormat": "switches_{{instance}}"
    }
   ]
  },
  {
   "title": "Time Spent Doing I/Os",
   "type": "graph",
   "description": "The time spent on I/O in the natural time of each second.（wall-clock time）",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_io_time_seconds_total{jobid=~\"$jobid\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_ IO time"
    }
   ]
  },
  {
   "title": "Network Sockstat",
   "type": "graph",
   "description": "TCP_alloc - Allocated sockets\n\nCurrEstab - TCP connections for which the current state is either ESTABLISHED or CLOSE- WAIT\n\nTCP_tw - Sockets wating close\n\nUDP_inuse - Udp sockets currently in use\n\nSockets_used - Sockets currently in use",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{jobid=~'$jobid'}",
     "legendFormat": "{{instance}}_CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{jobid=~'$jobid'}",
     "legendFormat": "{{instance}}_TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{jobid=~'$jobid'}",
     "legendFormat": "{{instance}}_Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{jobid=~'$jobid'}",
     "legendFormat": "{{instance}}_UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{jobid=~'$jobid'}",
     "legendFormat": "{{instance}}_TCP_alloc"
    }
   ]
  },
  {
   "title": "Disk IOps Completed",
   "type": "graph",
   "description": "Read/write completions per second",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 65 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_reads_completed_total{jobid=~\"$jobid\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Reads completed"
    },
    {
     "expr": "irate(node_disk_writes_completed_total{jobid=~\"$jobid\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Writes completed"
    }
   ]
  },
  {
   "title": "Disk R/W Time(Reference: less than 100ms)(beta)",
   "type": "graph",
   "description": "Time spent on each read/write operation",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 65 },
   "yaxes": [
    { "format": "s", "label": "Time. read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_time_seconds_total{jobid=~\"$jobid\"}[30m]) / irate(node_disk_reads_completed_total{jobid=~\"$jobid\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Read time"
    },
    {
     "expr": "irate(node_disk_write_time_seconds_total{jobid=~\"$jobid\"}[30m]) / irate(node_disk_writes_completed_total{jobid=~\"$jobid\"}[30m])",
     "legendFormat": "{{instance}}_{{device}}_Write time"
    }
   ]
  },
  {
   "title": "PCIe Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_PCIE_TX_THROUGHPUT{jobid=\"$jobid\"}",
     "legendFormat": "{{instance}}_GPU{{gpu}}_Tx"
    },
    {
     "expr": "DCGM_FI_DEV_PCIE_RX_THROUGHPUT{jobid=\"$jobid\"}",
     "legendFormat": "{{instance}}_GPU{{gpu}}_Rx"
    }
   ]
  },
  {
   "title": "NVLINK Bandwidth",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 71 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL{jobid=\"$jobid\"}[$__interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 71 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_POWER_USAGE{jobid=\"$jobid\"}",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_GPU_UTIL{jobid=\"$jobid\"}",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Mem Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "DCGM_FI_DEV_FB_USED{jobid=\"$jobid\"}",
     "legendFormat": "{{instance}} GPU {{gpu}}"
    }
   ]
  }
 ]
}