{
 "title": "Cluster Logs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Slurm", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Slurmctld",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /slurmctld/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Slurmd",
   "type": "logs",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /slurmd/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "ParallelCluster Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "computemgtd Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /computemgtd/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "clustermgtd Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 14 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /clustermgtd/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "clusterstatusmgtd Logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 14 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /clusterstatusmgtd/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Init", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "cloud-init",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /cloud-init/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Supervisord",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /supervisord/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "System Messages",
   "type": "logs",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /syslog/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Slurm Power saving", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Slurm Resume Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /slurm_resume/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Slurm Suspend Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message, @logStream\n| sort @timestamp desc\n| limit 20\n| filter @logStream like /slurm_suspend/",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Aggregate Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 } },
  {
   "title": "Cluster Logs (ALL)",
   "type": "logs",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 73 },
   "targets": [
    {
     "apiMode": "Logs",
     "expression": "fields @timestamp, @message \n| sort @timestamp desc\n| limit 20",
     "logGroupNames": [ "__LOG_GROUP__NAMES__" ],
     "queryMode": "Logs",
     "region": "__AWS_REGION__",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}